name: Taurus Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  perf-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check network connectivity
      run: curl -I --user '${{ secrets.BLAZEMETER_API_TOKEN }}' https://a.blazemeter.com/api/v4/accounts
    
    - name: bzt-taurus-action
      uses: tiagoms1/taurus-action@v1
      with:
        taurus_project_folder_name: 'taurus'
        taurus_command_line: blazedemo-csv-taurus.yml -report
        blazemeter_api_token: ${{ secrets.BLAZEMETER_API_TOKEN }}
